apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-fpm.fullname" . }}
  labels:
    {{- include "nginx-fpm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-fpm.selectorLabels" . | nindent 4 }}
