# permissions for end users to edit phpfpms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phpfpm-editor-role
rules:
- apiGroups:
  - runtime.com.cuppett
  resources:
  - phpfpms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runtime.com.cuppett
  resources:
  - phpfpms/status
  verbs:
  - get
